export const adminSections = [
  {
    id: "marketing",
    title: "Маркетинг / Источники",
    description: "UTM-визиты, регистрации, оплаты и редактируемый справочник рекламных каналов.",
    status: "Ready",
    href: "/marketing",
  },
  {
    id: "referrals",
    title: "Реферальная программа",
    description: "Отправители ссылок, регистрации, покупки подписок и начисления дополнительных примерок.",
    status: "Ready",
    href: "/referrals",
  },
  {
    id: "promo",
    title: "Промокоды",
    description: "Создание кодов, лимиты регистраций, ссылки для VK и отмена.",
    status: "Ready",
    href: "/promo",
  },
  {
    id: "leads",
    title: "Заявки раннего доступа",
    description: "Список лидов с лендинга, экспорт CSV, счётчик скидочных мест.",
    status: "Ready",
    href: "/leads",
  },
  {
    id: "reviews",
    title: "Отзывы",
    description: "Модерация отзывов после генерации, публикация на лендинге.",
    status: "Ready",
    href: "/reviews",
  },
  {
    id: "gallery",
    title: "Галерея",
    description: "Жалобы на посты, скрытие контента из public feed.",
    status: "Ready",
    href: "/gallery",
  },
  {
    id: "users",
    title: "Пользователи",
    description: "Тарифы, impersonation, профиль/аватары/примерки для поддержки, удаление аккаунтов.",
    status: "Ready",
    href: "/users",
  },
  {
    id: "ai-logs",
    title: "Логи AI / примерка",
    description: "Запросы и ответы noteapp-ai-integration в читаемом виде.",
    status: "Ready",
    href: "/ai-logs",
  },
  {
    id: "ai-prompts",
    title: "Промпт примерки",
    description: "Редактирование базовой русской части запроса к Grok (JSON с товаром дописывает система).",
    status: "Ready",
    href: "/ai-prompts",
  },
  {
    id: "ai-provider-errors",
    title: "Ошибки нейросетей",
    description: "Реестр ответов провайдеров: распознавание модерации и понятные сообщения пользователю.",
    status: "Ready",
    href: "/ai-provider-errors",
  },
  {
    id: "settings",
    title: "Настройки",
    description: "Блокировка Google OAuth и другие глобальные опции.",
    status: "Ready",
    href: "/settings",
  },
  {
    id: "providers",
    title: "AI providers",
    description: "Приоритеты noteapp-ai-integration, fallback и health.",
    status: "Ready",
    href: "/ai-providers",
  },
] as const;

export type AdminSection = (typeof adminSections)[number] & { href?: string };
