"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { Card, Button } from "@wibestyle/ui";
import { ApiError } from "@wibestyle/api-client";
import { useAppSession } from "@/components/providers/AppSessionProvider";

const styles = [
  ["smooth-bob", "Гладкий боб", "Плотный контур с мягко закруглёнными концами", "short"], ["a-bob", "А-боб", "Мягкое удлинение к лицу и объём на затылке", "short"], ["soft-pixie", "Пикси с мягкими перьями", "Подвижная макушка и лёгкая челка", "short"], ["french-bob", "Французский боб", "Компактный боб с разделённой чёлкой", "short"],
  ["slip-lob", "Slip lob", "До ключиц, скрытые слои и лёгкий разворот концов", "medium"], ["italian-bob", "Итальянский боб", "Мягкий округлый силуэт до основания шеи", "medium"], ["asym-bob", "Асимметричный боб", "Деликатная асимметрия и боковой пробор", "medium"], ["hidden-layers", "Лоб со скрытыми слоями", "Движение внутри формы, без явного каскада", "medium"],
  ["long-layers-curtain", "Длинные слои и чёлка-шторка", "Движение у лица без потери длины", "long"], ["u-cut", "Длинный U-срез", "Плотный мягкий контур для длинных волос", "long"], ["soft-wolf", "Мягкий wolf cut", "Подвижная макушка и сохранённая плотность", "long"], ["butterfly", "Стрижка Бабочка", "Воздушные уровни у лица", "long"],
  ["glass-hair", "Стеклянные волосы", "Гладкая укладка с зеркальным блеском", "styling"], ["sleek-ponytail", "Гладкий хвост", "Минималистичная укладка с чистым контуром", "styling"],
] as const;
const labels = { all: "Все", short: "Короткие", medium: "Средние", long: "Длинные", styling: "Укладки" };
type Filter = keyof typeof labels;
const asset = (id: string) => `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8080"}/assets/hairstyles/${id === "smooth-bob" ? "smooth-bob.webp" : id === "a-bob" ? "a-bob.webp" : id === "soft-pixie" ? "soft-pixie.webp" : id === "french-bob" ? "french-bob.webp" : id === "slip-lob" ? "slip-lob.webp" : id === "italian-bob" ? "italian-bob.webp" : id === "asym-bob" ? "asym-bob.webp" : id === "hidden-layers" ? "hidden-layers.webp" : id === "long-layers-curtain" ? "long-layers-curtain.webp" : id === "u-cut" ? "u-cut.webp" : id === "soft-wolf" ? "soft-wolf.webp" : id === "butterfly" ? "butterfly.jpg" : id === "glass-hair" ? "glass-hair.jpg" : "sleek-ponytail.jpg"}`;
export default function HairstyleTryOnClient() {
 const { api, ensureSession } = useAppSession(); const [filter,setFilter]=useState<Filter>("all"), [selected,setSelected]=useState<typeof styles[number]|null>(null), [file,setFile]=useState<File|null>(null), [loading,setLoading]=useState(false), [result,setResult]=useState<string|null>(null), [error,setError]=useState<string|null>(null);
 const list=useMemo(()=>styles.filter(s=>filter==="all"||s[3]===filter),[filter]);
 async function run(){ if(!selected||!file)return; if(!await ensureSession()){setError("Войдите в аккаунт, чтобы примерить причёску.");return;} setLoading(true);setError(null);try{const r=await api.createHairstyleTryOn(file,selected[0]);setResult(r.afterImageUrl);localStorage.setItem("wibestyle:hairstyles",JSON.stringify([{id:r.id,title:selected[1],imagePath:r.afterImageUrl,styleId:selected[0],createdAt:new Date().toISOString()},...JSON.parse(localStorage.getItem("wibestyle:hairstyles")??"[]")].slice(0,50)));}catch(e){setError(e instanceof ApiError?e.message:"Не удалось примерить причёску");}finally{setLoading(false);} }
 return <div className="mx-auto flex w-full max-w-6xl flex-col gap-6 px-4 py-10 md:px-8"><div><p className="text-eyebrow">AI-примерка волос</p><h1 className="text-display mt-2 text-4xl">Стрижки и причёски</h1><p className="text-body mt-2 max-w-2xl">Выбери образец из подборки и загрузи отдельный портрет: лицо прямо, от макушки до плеч, без очков и фильтров.</p></div><div className="flex flex-wrap gap-2">{(Object.keys(labels) as Filter[]).map(k=><button key={k} onClick={()=>setFilter(k)} className={`rounded-full px-4 py-2 text-sm font-medium ${filter===k?"bg-[#ff1fa2] text-white":"border border-[#ffd1ed] bg-white text-[#6d6273]"}`}>{labels[k]}</button>)}</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{list.map(s=><button key={s[0]} onClick={()=>setSelected(s)} className={`overflow-hidden rounded-[24px] border bg-white text-left ${selected?.[0]===s[0]?"border-[#ff1fa2] ring-2 ring-[#ffd1ed]":"border-[#ffd1ed]"}`}><img src={asset(s[0])} alt={s[1]} className="aspect-[4/5] w-full object-cover"/><span className="block p-4"><b>{s[1]}</b><small className="mt-1 block text-[#6d6273]">{s[2]}</small></span></button>)}</div>{selected?<Card><h2 className="text-display-md text-2xl">{selected[1]}</h2><p className="text-body mt-2">Загрузи портрет для примерки. Он не меняет аватар для одежды.</p><input className="mt-4 block text-sm" type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]??null)}/><Button className="mt-4" disabled={!file||loading} onClick={()=>void run()}>{loading?"Примеряем…":"Примерить на себе"}</Button>{error?<p className="mt-3 text-sm text-red-600">{error}</p>:null}{result?<img src={`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8080"}${result}`} alt="Результат примерки" className="mt-5 max-w-md rounded-[24px]"/>:null}</Card>:null}<Link href="/try-on" className="text-link">← К способам примерки</Link></div>;
}
